name: Run Tests and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Gunicorn and Nginx dependencies
          sudo apt-get install -y nginx
          pip install gunicorn

      - name: Run tests
        run: pytest

      - name: Deploy to DigitalOcean
        if: success() # Only deploy if the tests pass successfully
        run: |
          ssh username@167.71.59.87 'cd /home/simple-app/ && git pull origin main && pip install -r requirements.txt && systemctl restart simple-app'
